server:
  address: 0.0.0.0
  port: 8089

spring:
  application:
    name: communication-service
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:communication-service:8089
